% scatter(tdc,idf,'.');
% labels=1:18;
% boxplot(tdc,journal,'labels',labels,'Widths',0.5, 'symbol','o', 'colors','k');
% xlabel('Journal');
% ylabel('TDC');
% set(gca,...
%     'YTick',-2:5,...
%     'FontUnits','points',...
%     'FontWeight','bold',...
%     'FontSize',20,...
%     'FontName','Arial')
plot(Journal,x2013, '-ro',Journal, x2014,'-g+',Journal, x2015,'-y*',Journal, x2016,'-bs',Journal, x2017,'-k^')
xlabel('Journal');
ylabel('Estimated Marginal Means of TDC');
set(gca,...
    'YTick',0.6000:1.1000,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',20,...
    'FontName','Arial')